"""empty message

Revision ID: c8099e7b7a21
Revises: f3f439787c35
Create Date: 2019-02-15 07:59:53.616675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8099e7b7a21"
down_revision = "f3f439787c35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET admin=False")
    op.alter_column("users", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
